# Data Science Project

**College/University Name**: _CICCC - Cornerstone International Community College of Canada_  
**Course**: _Machine Learning_  
**Instructor**: _Austin Egbal_  
**Student Names**: _Amir Lima Oliveira_, _Otávio Londero_, _Yuan Chan_

---

#### Dataset Overview
- **Source:** [[Housing Prices Competition for Kaggle Learn Users](https://www.kaggle.com/competitions/home-data-for-ml-course/data)]
- **Description:** Dataset of Ames housing with 80 features including property size, quality, location, and amenities to predict final sale price in dollars (target variable).
- **Credits:** DanB. Housing Prices Competition for Kaggle Learn Users. https://kaggle.com/competitions/home-data-for-ml-course, 2018. Kaggle.

---

#### The purpose of this notebook is to explore the features, engineer new features based on the target variable (SalePrice) and optimize existing ones.

## Table of Contents
### 1. [Import Libraries](#import-libraries)

In [72]:
import os
import zipfile
# Packages for data manipulation
import pandas as pd
import numpy as np

# Packages for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# APIs for data access
# import kaggle
# from kaggle.api.kaggle_api_extended import KaggleApi

# Packages for machine learning
import sklearn as sk

# Packages for data preprocessing
from sklearn.preprocessing import  RobustScaler, LabelEncoder

### 2. [Load & Inspect Data](#load--inspect-data)

In [73]:
# # Authenticate and download dataset from Kaggle
# api = KaggleApi()
# api.authenticate()

# # Create a directory to store the dataset
# os.makedirs('../data/data_from_kaggle', exist_ok=True)
# extract_to = '../data/data_from_kaggle'
# zip_path = '../data/data_from_kaggle/home-data-for-ml-course.zip'

# # Download the dataset from Kaggle
# kaggle.api.competition_download_files('home-data-for-ml-course', path='../data/data_from_kaggle')

# # Extract the downloaded zip file
# with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#     zip_ref.extractall(extract_to)
    
# Load both dataset and concat in one
#df_train = pd.read_csv('../data/data_from_kaggle/train.csv')
#df_test = pd.read_csv('../data/data_from_kaggle/test.csv')
#df = pd.concat([df_train, df_test], axis=0)
test_dataset_for_submission = pd.read_csv('./data/data_from_kaggle/test.csv')
train_dataset_with_target = pd.read_csv('./data/data_from_kaggle/train.csv')

   - [Shape](#shape)

In [74]:
# print(f"Train shape: {df_train.shape}")
# print(f"Test shape: {df_test.shape}")
# print(f"Combined shape: {df.shape}")
print(f"Test shape: {test_dataset_for_submission.shape}")
print(f"Test shape: {train_dataset_with_target.shape}")

Test shape: (1459, 80)
Test shape: (1460, 81)

   - [Missing Values](#missing-values) <code> I'll handle those at topic __5.Feature Engineering__ </code>

test

In [75]:
test_dataset_for_submission.isnull().sum().sort_values(ascending=False).head(20)

PoolQC          1456
MiscFeature     1408
Alley           1352
Fence           1169
MasVnrType       894
FireplaceQu      730
LotFrontage      227
GarageYrBlt       78
GarageQual        78
GarageFinish      78
GarageCond        78
GarageType        76
BsmtCond          45
BsmtQual          44
BsmtExposure      44
BsmtFinType1      42
BsmtFinType2      42
MasVnrArea        15
MSZoning           4
BsmtHalfBath       2
dtype: int64

train

In [76]:
train_dataset_with_target.isnull().sum().sort_values(ascending=False).head(20)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageYrBlt       81
GarageCond        81
GarageType        81
GarageFinish      81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
Id                 0
dtype: int64

   - [Data Types](#data-types)

test

In [77]:
test_dataset_for_submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     565 non-null    object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

train

In [78]:
train_dataset_with_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

   - [Preview Data](#preview-data)

test

In [79]:
test_dataset_for_submission.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal

train

In [80]:
train_dataset_with_target.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

---

### 3. [Data Cleaning](#data-cleaning)

   - [Drop Duplicates](#drop-duplicates)

test

In [81]:
# Any duplicate rows were found in the dataset.
test_dataset_for_submission[test_dataset_for_submission.duplicated()]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition]
Index: []

[0 rows x 80 columns]

train

In [82]:
# Any duplicate rows were found in the dataset.
train_dataset_with_target[train_dataset_with_target.duplicated()]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

   - [Standardize Text and Formats](#standardize-text-and-formats)
      - <code> No need for text and format standardization such as Lowercasing / Uppercasing, Trimming whitespace, Removing special characters or Handling encoding issues </code>

   - [Convert Data Types](#convert-data-types)
      - <code> No need for convertions </code>

---

### Handling Missing Data

test

In [83]:
# 1. Fill absence indicators 
none_cols = ['PoolQC','MiscFeature','Alley','Fence','FireplaceQu',
             'GarageType','GarageFinish','GarageQual','GarageCond',
             'BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1',
             'BsmtFinType2','MasVnrType']
test_dataset_for_submission[none_cols] = test_dataset_for_submission[none_cols].fillna('None')

# 2. LotFrontage: fill missing values with median by neighborhood
lotfrontage_median = test_dataset_for_submission.groupby('Neighborhood')['LotFrontage'].transform('median')
test_dataset_for_submission['LotFrontage'] = test_dataset_for_submission['LotFrontage'].fillna(lotfrontage_median)

# 3. GarageYrBlt: fill with median year
test_dataset_for_submission['GarageYrBlt'] = test_dataset_for_submission['GarageYrBlt'].fillna(test_dataset_for_submission['GarageYrBlt'].median())

# 4. MasVnrArea: fill with 0
test_dataset_for_submission['MasVnrArea'] = test_dataset_for_submission['MasVnrArea'].fillna(0)

# 5. Electrical: fill with mode
test_dataset_for_submission['Electrical'] = test_dataset_for_submission['Electrical'].fillna(test_dataset_for_submission['Electrical'].mode()[0])

train

In [84]:
# 1. Fill absence indicators 
none_cols = ['PoolQC','MiscFeature','Alley','Fence','FireplaceQu',
             'GarageType','GarageFinish','GarageQual','GarageCond',
             'BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1',
             'BsmtFinType2','MasVnrType']
train_dataset_with_target[none_cols] = train_dataset_with_target[none_cols].fillna('None')

# 2. LotFrontage: fill missing values with median by neighborhood
lotfrontage_median = train_dataset_with_target.groupby('Neighborhood')['LotFrontage'].transform('median')
train_dataset_with_target['LotFrontage'] = train_dataset_with_target['LotFrontage'].fillna(lotfrontage_median)

# 3. GarageYrBlt: fill with median year
train_dataset_with_target['GarageYrBlt'] = train_dataset_with_target['GarageYrBlt'].fillna(train_dataset_with_target['GarageYrBlt'].median())

# 4. MasVnrArea: fill with 0
train_dataset_with_target['MasVnrArea'] = train_dataset_with_target['MasVnrArea'].fillna(0)

# 5. Electrical: fill with mode
train_dataset_with_target['Electrical'] = train_dataset_with_target['Electrical'].fillna(train_dataset_with_target['Electrical'].mode()[0])

- In order to don't miss any value, I decided to fill it with __"None"__ for the houses that doesn't have some housing features details, such as basement, pool, garage and so on.
- Also for the __"Linear feet of street connected to property"__ and __Year garage was built__,  miss values, I filled it with the __median__
- For the __Masonry veneer area in square feet__ The best option, based on the column describe, is to fill the missing values with "0". (Most of the houses doesn't have masonry veneer).
- The __"Eletrical feature"__ is categorical, so based on it, I used the __"mode"__ to fill the missing data.

___
### Creating Custom Features

| New Column Name | Features Used to Create       | Meaning                                                                 |
|-----------------|-------------------------------|-------------------------------------------------------------------------|
| `SQR_RATIO`     | `GrLivArea`; `LotArea`        | Above grade (ground) living area square feet / Lot size in square feet  |
| `SQR_ROOM`      | `GrLivArea`; `TotRmsAbvGrd`| Above grade (ground) living area square feet / Total rooms above grade (does not include bathrooms)|
| `TOTAL_ROOMS`| `TotRmsAbvGrd`;`FullBath`;`HalfBath`;`BsmtFullBath`; `BsmtHalfBath`| Total rooms above grade + Full bathrooms and Half above grade + Basement full bathrooms and half bath|
|`TOTAL_AREA`|`GrLivArea`;`TotalBsmtSF`| Above ground living area square feet + Total square feet of basement area|
| `TOTAL_VOL`|`MasVnrArea`; `GrLivArea`|  Exterior veneer with the size of the living area, scaled down|

test

In [85]:
test_dataset_for_submission["SQR_RATIO"] = test_dataset_for_submission["GrLivArea"] /  test_dataset_for_submission["LotArea"]
test_dataset_for_submission["SQR_ROOM"] = test_dataset_for_submission["GrLivArea"] / test_dataset_for_submission["TotRmsAbvGrd"]
test_dataset_for_submission["TOTAL_ROOMS"] = test_dataset_for_submission["TotRmsAbvGrd"] + test_dataset_for_submission["FullBath"] + test_dataset_for_submission["HalfBath"] + test_dataset_for_submission["BsmtFullBath"] + test_dataset_for_submission["BsmtHalfBath"]
test_dataset_for_submission["TOTAL_AREA"] = test_dataset_for_submission["GrLivArea"] + test_dataset_for_submission["TotalBsmtSF"]
test_dataset_for_submission["TOTAL_VOL"]= (test_dataset_for_submission["MasVnrArea"] * np.sqrt(df["GrLivArea"])) / 4

train

In [86]:
train_dataset_with_target["SQR_RATIO"] = train_dataset_with_target["GrLivArea"] /  train_dataset_with_target["LotArea"]
train_dataset_with_target["SQR_ROOM"] = train_dataset_with_target["GrLivArea"] / train_dataset_with_target["TotRmsAbvGrd"]
train_dataset_with_target["TOTAL_ROOMS"] = train_dataset_with_target["TotRmsAbvGrd"] + train_dataset_with_target["FullBath"] + train_dataset_with_target["HalfBath"] + train_dataset_with_target["BsmtFullBath"] + train_dataset_with_target["BsmtHalfBath"]
train_dataset_with_target["TOTAL_AREA"] = train_dataset_with_target["GrLivArea"] + train_dataset_with_target["TotalBsmtSF"]
train_dataset_with_target["TOTAL_VOL"]= (train_dataset_with_target["MasVnrArea"] * np.sqrt(train_dataset_with_target["GrLivArea"])) / 4

- In our dataset, we experimented with feature engineering by creating new variables. However, the results were not successful, instead of improving model performance, the additional features actually made it **worse**. We suspected this was due to redundance, as the new features were essentially derived from existing ones and provided overlapping information. To test this, we dropped the original columns used to create those features, but even then the performance did not improve. Given these outcomes, we decided to set aside feature engineering for now and continue working with the dataset in its original form.

___
   - [Encoding Categorical Variables](#encoding-categorical-variables)

test

In [87]:
label_encoder = LabelEncoder()
# Encode categorical features

categorical_features = test_dataset_for_submission.select_dtypes(include=['object'])

for col in categorical_features.columns:
    test_dataset_for_submission[col] = label_encoder.fit_transform(test_dataset_for_submission[col].astype(str))

# Checking if label encoding was successful
test_dataset_for_submission.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SQR_RATIO,SQR_ROOM,TOTAL_ROOMS,TOTAL_AREA,TOTAL_VOL
0,1461,20,2,80.0,11622,1,1,3,3,0,...,0,6,2010,8,4,0.077095,179.2,6.0,1778.0,0.000000
1,1462,20,3,81.0,14267,1,1,0,3,0,...,12500,6,2010,8,4,0.093152,221.5,8.0,2658.0,984.297211

train

In [88]:
label_encoder = LabelEncoder()
# Encode categorical features

categorical_features = train_dataset_with_target.select_dtypes(include=['object'])

for col in categorical_features.columns:
    train_dataset_with_target[col] = label_encoder.fit_transform(train_dataset_with_target[col].astype(str))

# Checking if label encoding was successful
train_dataset_with_target.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MoSold,YrSold,SaleType,SaleCondition,SalePrice,SQR_RATIO,SQR_ROOM,TOTAL_ROOMS,TOTAL_AREA,TOTAL_VOL
0,1,60,3,65.0,8450,1,1,3,3,0,...,2,2008,8,4,208500,0.202367,213.750000,12,2566,2026.255167
1,2,20,3,80.0,9600,1,1,3,3,0,...,5,2007,8,4,181500,0.131458,210.333333,9,2524,0.000000

___

#### Correlation Analysis

- Using all the features of the data, witch one is correlating the most with my target variable (SalePrice)?

test

not correlating with 'SalePrice' because test dataset doesn't have the target feature

train

In [89]:
correlations = train_dataset_with_target.corr()
print(correlations['SalePrice'].apply(abs).sort_values(ascending = False).iloc[:60])

selected_columns = []

SalePrice        1.000000
OverallQual      0.790982
TOTAL_AREA       0.778959
GrLivArea        0.708624
TOTAL_ROOMS      0.644795
GarageCars       0.640409
ExterQual        0.636884
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
BsmtQual         0.593734
KitchenQual      0.589189
FullBath         0.560664
SQR_ROOM         0.540645
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
TOTAL_VOL        0.519832
YearRemodAdd     0.507101
MasVnrArea       0.472614
Fireplaces       0.466929
GarageYrBlt      0.466754
GarageFinish     0.425684
GarageType       0.415283
HeatingQC        0.400178
BsmtFinSF1       0.386420
Foundation       0.382479
LotFrontage      0.349876
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
BsmtExposure     0.309043
HalfBath         0.284108
LotArea          0.263843
LotShape         0.255580
CentralAir       0.251328
GarageCond       0.246705
Electrical       0.234945
PavedDrive       0.231357
BsmtFullBath     0.227122
RoofStyle        0.222405
BsmtUnfSF        0.214479
SaleCondition    0.213092
Neighborhood     0.210851
GarageQual       0.205963
HouseStyle       0.180163
BedroomAbvGr     0.168213
MSZoning         0.166872
Fence            0.140640
KitchenAbvGr     0.135907
RoofMatl         0.132383
EnclosedPorch    0.128578
PoolQC           0.126070
ExterCond        0.117303
Functional       0.115328
ScreenPorch      0.111447
Exterior2nd      0.103766
Exterior1st      0.103551
Heating          0.098812
BsmtFinType1     0.098734
FireplaceQu      0.097176
Name: SalePrice, dtype: float64

- Selecting columns with a correlation above 0.1 to reduce the number of features, thereby decreasing the computational resources required for future machine learning tasks.

test

In [90]:
for col in test_dataset_for_submission.columns:
    if abs(correlations[col]['SalePrice']) > 0.10:
        selected_columns.append(col)

df_selected_test = test_dataset_for_submission[selected_columns]
df_selected_test.head(2)

,MSZoning,LotFrontage,LotArea,LotShape,Neighborhood,HouseStyle,OverallQual,YearBuilt,YearRemodAdd,RoofStyle,...,OpenPorchSF,EnclosedPorch,ScreenPorch,PoolQC,Fence,SaleCondition,SQR_ROOM,TOTAL_ROOMS,TOTAL_AREA,TOTAL_VOL
0,2,80.0,11622,3,12,2,5,1961,1961,1,...,0,0,120,2,2,4,179.2,6.0,1778.0,0.000000
1,3,81.0,14267,0,12,2,6,1958,1958,3,...,36,0,0,2,4,4,221.5,8.0,2658.0,984.297211

train

In [91]:
for col in train_dataset_with_target.columns:
    if abs(correlations[col]['SalePrice']) > 0.10:
        selected_columns.append(col)

df_selected_train = train_dataset_with_target[selected_columns]
df_selected_train.head(2)

,MSZoning,LotFrontage,LotArea,LotShape,Neighborhood,HouseStyle,OverallQual,YearBuilt,YearRemodAdd,RoofStyle,...,EnclosedPorch,ScreenPorch,PoolQC,Fence,SaleCondition,SalePrice,SQR_ROOM,TOTAL_ROOMS,TOTAL_AREA,TOTAL_VOL
0,3,65.0,8450,3,5,5,7,2003,2003,1,...,0,0,3,4,4,208500,213.750000,12,2566,2026.255167
1,3,80.0,9600,3,24,2,6,1976,1976,1,...,0,0,3,4,4,181500,210.333333,9,2524,0.000000

In [92]:
df_selected_test.shape, df_selected_train.shape

((1459, 56), (1460, 113))

In [93]:
df_selected_test.dtypes, df_selected_train.dtypes

(MSZoning           int32
 LotFrontage      float64
 LotArea            int64
 LotShape           int32
 Neighborhood       int32
 HouseStyle         int32
 OverallQual        int64
 YearBuilt          int64
 YearRemodAdd       int64
 RoofStyle          int32
 RoofMatl           int32
 Exterior1st        int32
 Exterior2nd        int32
 MasVnrArea       float64
 ExterQual          int32
 ExterCond          int32
 Foundation         int32
 BsmtQual           int32
 BsmtExposure       int32
 BsmtFinSF1       float64
 BsmtUnfSF        float64
 TotalBsmtSF      float64
 HeatingQC          int32
 CentralAir         int32
 Electrical         int32
 1stFlrSF           int64
 2ndFlrSF           int64
 GrLivArea          int64
 BsmtFullBath     float64
 FullBath           int64
 HalfBath           int64
 BedroomAbvGr       int64
 KitchenAbvGr       int64
 KitchenQual        int32
 TotRmsAbvGrd       int64
 Functional         int32
 Fireplaces         int64
 GarageType         int32
 GarageYrBlt      float64
 GarageFinish       int32
 GarageCars       float64
 GarageArea       float64
 GarageQual         int32
 GarageCond         int32
 PavedDrive         int32
 WoodDeckSF         int64
 OpenPorchSF        int64
 EnclosedPorch      int64
 ScreenPorch        int64
 PoolQC             int32
 Fence              int32
 SaleCondition      int32
 SQR_ROOM         float64
 TOTAL_ROOMS      float64
 TOTAL_AREA       float64
 TOTAL_VOL        float64
 dtype: object,
 MSZoning          int32
 LotFrontage     float64
 LotArea           int64
 LotShape          int32
 Neighborhood      int32
                  ...
 SalePrice         int64
 SQR_ROOM        float64
 TOTAL_ROOMS       int64
 TOTAL_AREA        int64
 TOTAL_VOL       float64
 Length: 113, dtype: object)

___

   - [Feature Transformation (Scaling, Normalization)](#feature-transformation-scaling-normalization)

test

In [94]:
scaler = RobustScaler()
scaled_array = scaler.fit_transform(df_selected_test) 

df_scaled_test = pd.DataFrame(scaled_array, columns=df_selected_test.columns)
df_scaled_test.head(2)

,MSZoning,LotFrontage,LotArea,LotShape,Neighborhood,HouseStyle,OverallQual,YearBuilt,YearRemodAdd,RoofStyle,...,OpenPorchSF,EnclosedPorch,ScreenPorch,PoolQC,Fence,SaleCondition,SQR_ROOM,TOTAL_ROOMS,TOTAL_AREA,TOTAL_VOL
0,-1.0,0.50,0.538713,0.0,0.0,0.0,-0.5,-0.2500,-0.756098,0.0,...,-0.388889,0.0,120.0,0.0,-2.0,0.0,-0.779293,-1.000000,-0.662437,0.000000
1,0.0,0.55,1.179692,-1.0,0.0,0.0,0.0,-0.3125,-0.829268,2.0,...,0.111111,0.0,0.0,0.0,0.0,0.0,-0.079913,-0.333333,0.230964,0.651744

train

In [95]:
scaler = RobustScaler()
scaled_array = scaler.fit_transform(df_selected_train) 

df_scaled_train = pd.DataFrame(scaled_array, columns=df_selected_train.columns)
df_scaled_train.head(2)

,MSZoning,LotFrontage,LotArea,LotShape,Neighborhood,HouseStyle,OverallQual,YearBuilt,YearRemodAdd,RoofStyle,...,EnclosedPorch,ScreenPorch,PoolQC,Fence,SaleCondition,SalePrice,SQR_ROOM,TOTAL_ROOMS,TOTAL_AREA,TOTAL_VOL
0,0.0,-0.25,-0.254076,0.0,-0.7,1.0,0.5,0.652174,0.243243,0.0,...,0.0,0.0,0.0,0.0,0.0,0.541506,-0.223265,1.0,0.087481,1.34694
1,0.0,0.50,0.030015,0.0,1.2,0.0,0.0,0.065217,-0.486486,0.0,...,0.0,0.0,0.0,0.0,0.0,0.220173,-0.283094,0.0,0.045249,0.00000

test

not dropping 'SalePrice' because test dataset doesn't have the target feature

In [96]:
# # Dropping the target variable from the features.

# df_scaled_test.drop(columns=['SalePrice'], inplace=True)
# df_scaled_test.shape

train

In [97]:
# Dropping the target variable from the features.

df_scaled_train.drop(columns=['SalePrice'], inplace=True)
df_scaled_train.shape

(1460, 112)

___
#### Saving the cleaned data into other file

In [100]:
# os.makedirs('../data/cleaned_data', exist_ok=True) 
df_scaled_test.to_csv('./data/cleaned_data/preprocessed_test_data_for_submission.csv', index=False)